# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=10)),
                ('resNo', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ribsBox', models.PositiveIntegerField(default=0)),
                ('vegetarianBox', models.PositiveIntegerField(default=0)),
                ('vat', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
